<?php

use Illuminate\Database\Seeder;

class SpecialisatievakkenSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //
        DB::table('specialisatievaks')->insert([
            [
                'code' => 'IIPDBAM',
                'naam' => 'Project inleiding BDaM',
                'ec' => 10,
                'jaar_id' => 1,
                'specialisatie_id' => 2,
            ],
            [
                'code' => 'IIPMEDT',
                'naam' => 'Project inleiding MedT',
                'ec' => 10,
                'jaar_id' => 1,
                'specialisatie_id' => 1,
            ],
            [
                'code' => 'IIPSEN',
                'naam' => 'Project inleiding SE',
                'ec' => 10,
                'jaar_id' => 1,
                'specialisatie_id' => 4,
            ],
            [
                'code' => 'IIPFIT',
                'naam' => 'Project inleiding FICT',
                'ec' => 10,
                'jaar_id' => 1,
                'specialisatie_id' => 3,
            ],


            [
                'code' => 'IPBDAM2',
                'naam' => 'Project Business DataManagement 2',
                'ec' => 6,
                'jaar_id' => 2,
                'specialisatie_id' => 2,
            ],
            [
                'code' => 'IPRODAM',
                'naam' => 'Proces- en Data-modelleren',
                'ec' => 3,
                'jaar_id' => 2,
                'specialisatie_id' => 2,
            ],
            [
                'code' => 'IPBDAM3',
                'naam' => 'Project Business DataManagement 3',
                'ec' => 6,
                'jaar_id' => 2,
                'specialisatie_id' => 2,
            ],
            [
                'code' => 'IDAAN1',
                'naam' => 'Data-analyse Basis',
                'ec' => 3,
                'jaar_id' => 2,
                'specialisatie_id' => 2,
            ],
            [
                'code' => 'IPDBAM4',
                'naam' => 'Project Business DataManagement 4',
                'ec' => 6,
                'jaar_id' => 2,
                'specialisatie_id' => 2,
            ],
            [
                'code' => 'IDAM',
                'naam' => 'Datamanagement',
                'ec' => 3,
                'jaar_id' => 2,
                'specialisatie_id' => 2,
            ],
            [
                'code' => 'IPBDAM5',
                'naam' => 'Project Business DataManagement 5',
                'ec' => 6,
                'jaar_id' => 2,
                'specialisatie_id' => 2,
            ],
            [
                'code' => 'IBUID',
                'naam' => 'Business Intelligence & Data Warehousing',
                'ec' => 3,
                'jaar_id' => 2,
                'specialisatie_id' => 2,
            ],
            [
                'code' => 'IPDAMH',
                'naam' => 'Hoofdfaseproject Business DataManagement',
                'ec' => 9,
                'jaar_id' => 3,
                'specialisatie_id' => 2,
            ],
            [
                'code' => 'IDARE',
                'naam' => 'Data Realisatie',
                'ec' => 3,
                'jaar_id' => 3,
                'specialisatie_id' => 2,
            ],
            [
                'code' => 'IDAAN2',
                'naam' => 'Data-analyse 2',
                'ec' => 3,
                'jaar_id' => 3,
                'specialisatie_id' => 2,
            ],
            [
                'code' => 'IDARCH',
                'naam' => 'Data Architectuur',
                'ec' => 3,
                'jaar_id' => 3,
                'specialisatie_id' => 2,
            ],
            [
                'code' => 'IWLS',
                'naam' => 'Stage',
                'ec' => 30,
                'jaar_id' => 3,
                'specialisatie_id' => 2,
            ],
            [
                'code' => 'IWLA',
                'naam' => 'Afstudeerverslag',
                'ec' => 30,
                'jaar_id' => 3,
                'specialisatie_id' => 2,
            ],


            [
                'code' => 'IPMEDT2',
                'naam' => 'Project Mediatechnologie 2',
                'ec' => 6,
                'jaar_id' => 2,
                'specialisatie_id' => 1,
            ],
            [
                'code' => 'IMTD1',
                'naam' => 'Mediatechnlogisch Design 1 ',
                'ec' => 3,
                'jaar_id' => 2,
                'specialisatie_id' => 1,
            ],
            [
                'code' => 'IPMEDT3',
                'naam' => 'Project Mediatechnologie 3',
                'ec' => 6,
                'jaar_id' => 2,
                'specialisatie_id' => 1,
            ],
            [
                'code' => 'IMTUE',
                'naam' => 'Mediatechnologie Usability Engineering',
                'ec' => 3,
                'jaar_id' => 2,
                'specialisatie_id' => 1,
            ],
            [
                'code' => 'IPMEDT5',
                'naam' => 'Project Mediatechnologie 5',
                'ec' => 6,
                'jaar_id' => 2,
                'specialisatie_id' => 1,
            ],
            [
                'code' => 'IMTCM',
                'naam' => 'Mediatechnologie Creative marketing',
                'ec' => 3,
                'jaar_id' => 2,
                'specialisatie_id' => 1,
            ],
            [
                'code' => 'IPMEDT4',
                'naam' => 'Project Mediatechnologie 4',
                'ec' => 6,
                'jaar_id' => 2,
                'specialisatie_id' => 1,
            ],
            [
                'code' => 'IMTPMD',
                'naam' => 'Mediatechnology Programming for Mobile Devices',
                'ec' => 3,
                'jaar_id' => 2,
                'specialisatie_id' => 1,
            ],
            [
                'code' => 'IPMEDTH',
                'naam' => 'Hoofdfaseproject Mediatechnologie',
                'ec' => 9,
                'jaar_id' => 3,
                'specialisatie_id' => 1,
            ],
            [
                'code' => 'IMTUX',
                'naam' => 'Mediatechnologie User Experience',
                'ec' => 3,
                'jaar_id' => 3,
                'specialisatie_id' => 1,
            ],
            [
                'code' => 'IMTHE1',
                'naam' => 'Mediatechnologie Hardware Engineering',
                'ec' => 3,
                'jaar_id' => 3,
                'specialisatie_id' => 1,
            ],
            [
                'code' => 'IMTHMI',
                'naam' => 'Human-Machine-interaction',
                'ec' => 3,
                'jaar_id' => 3,
                'specialisatie_id' => 1,
            ],
            [
                'code' => 'IWLS',
                'naam' => 'Stage',
                'ec' => 30,
                'jaar_id' => 3,
                'specialisatie_id' => 1,
            ],
            [
                'code' => 'IWLA',
                'naam' => 'Afstudeerverslag',
                'ec' => 30,
                'jaar_id' => 3,
                'specialisatie_id' => 1,
            ],


            [
                'code' => 'IPSEN2',
                'naam' => 'Project Software Engineering 2',
                'ec' => 6,
                'jaar_id' => 2,
                'specialisatie_id' => 4,
            ],
            [
                'code' => 'IRDM',
                'naam' => 'Relationele Databases Modelleren',
                'ec' => 3,
                'jaar_id' => 2,
                'specialisatie_id' => 4,
            ],
            [
                'code' => 'IPSEN3',
                'naam' => 'Project Software Engineering 3',
                'ec' => 6,
                'jaar_id' => 2,
                'specialisatie_id' => 4,
            ],
            [
                'code' => 'IPRWC',
                'naam' => 'Programmeren in een webcontext',
                'ec' => 3,
                'jaar_id' => 2,
                'specialisatie_id' => 4,
            ],
            [
                'code' => 'IPSEN4',
                'naam' => 'Project Software Engineering 4',
                'ec' => 6,
                'jaar_id' => 2,
                'specialisatie_id' => 4,
            ],
            [
                'code' => 'ILG1',
                'naam' => 'Logica',
                'ec' => 3,
                'jaar_id' => 2,
                'specialisatie_id' => 4,
            ],
            [
                'code' => 'IPSEN5',
                'naam' => 'Project Software Engineering 5',
                'ec' => 6,
                'jaar_id' => 2,
                'specialisatie_id' => 4,
            ],
            [
                'code' => 'IIAD',
                'naam' => 'Inleiding Algoritmen en Datastructuren',
                'ec' => 3,
                'jaar_id' => 2,
                'specialisatie_id' => 4,
            ],
            [
                'code' => 'IPSENH',
                'naam' => 'Hoofdfaseproject Software Engineering',
                'ec' => 9,
                'jaar_id' => 3,
                'specialisatie_id' => 4,
            ],
            [
                'code' => 'IAD1',
                'naam' => 'Algoritmen en Datastructuren 1',
                'ec' => 3,
                'jaar_id' => 3,
                'specialisatie_id' => 4,
            ],
            [
                'code' => 'ICP',
                'naam' => 'Concepten in Programmeertalen',
                'ec' => 3,
                'jaar_id' => 3,
                'specialisatie_id' => 4,
            ],
            [
                'code' => 'ITEST',
                'naam' => 'Testen van software',
                'ec' => 3,
                'jaar_id' => 3,
                'specialisatie_id' => 4,
            ],
            [
                'code' => 'IWLS',
                'naam' => 'Stage',
                'ec' => 30,
                'jaar_id' => 3,
                'specialisatie_id' => 4,
            ],
            [
                'code' => 'IWLA',
                'naam' => 'Afstudeerverslag',
                'ec' => 30,
                'jaar_id' => 3,
                'specialisatie_id' => 4,
            ],


            [
                'code' => 'IPFJURI',
                'naam' => 'Juridisch Forenscisch Project',
                'ec' => 3,
                'jaar_id' => 2,
                'specialisatie_id' => 3,
            ],
            [
                'code' => 'IFRCHT',
                'naam' => 'Recht voor forensisch Iters',
                'ec' => 3,
                'jaar_id' => 2,
                'specialisatie_id' => 3,
            ],
            [
                'code' => 'IPFNET',
                'naam' => 'Project Netwerkonderzoek',
                'ec' => 3,
                'jaar_id' => 2,
                'specialisatie_id' => 3,
            ],
            [
                'code' => 'IFNWR',
                'naam' => 'Netwerkonderzoek',
                'ec' => 3,
                'jaar_id' => 2,
                'specialisatie_id' => 3,
            ],
            [
                'code' => 'IPFIT5',
                'naam' => 'Project Forensisch ICT 5',
                'ec' => 3,
                'jaar_id' => 2,
                'specialisatie_id' => 3,
            ],
            [
                'code' => 'IFMA',
                'naam' => 'Malware analyse in systemen',
                'ec' => 3,
                'jaar_id' => 2,
                'specialisatie_id' => 3,
            ],
            [
                'code' => 'IPFIT4',
                'naam' => 'Project Forensisch ICT 4',
                'ec' => 3,
                'jaar_id' => 2,
                'specialisatie_id' => 3,
            ],
            [
                'code' => 'IFTON',
                'naam' => 'Technisch Onderzoek',
                'ec' => 3,
                'jaar_id' => 2,
                'specialisatie_id' => 3,
            ],
            [
                'code' => 'IPFIT6',
                'naam' => 'Project Forensisch ICT 6',
                'ec' => 3,
                'jaar_id' => 2,
                'specialisatie_id' => 3,
            ],
            [
                'code' => 'IFOSI',
                'naam' => 'Internetonderzoek',
                'ec' => 3,
                'jaar_id' => 2,
                'specialisatie_id' => 3,
            ],
            [
                'code' => 'IPFIT7',
                'naam' => 'Project Forensisch ICT 7',
                'ec' => 3,
                'jaar_id' => 2,
                'specialisatie_id' => 3,
            ],
            [
                'code' => 'IFEDY',
                'naam' => 'E-Discovery',
                'ec' => 3,
                'jaar_id' => 2,
                'specialisatie_id' => 3,
            ],
            [
                'code' => 'IWLS',
                'naam' => 'Stage',
                'ec' => 3,
                'jaar_id' => 2,
                'specialisatie_id' => 3,
            ],
            [
                'code' => 'IWLA',
                'naam' => 'Afstudeerverslag',
                'ec' => 3,
                'jaar_id' => 2,
                'specialisatie_id' => 3,
            ],
        ]);
    }
}
